config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/insider/search')

  namespace :insider do
    root to: redirect('/insider/search')

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'logout', to: 'sessions#destroy'

    namespace :search, module: 'searches' do
      root to: 'dashboard#show'

      resources 'apartments', only: %w(index show)
      resources 'franchise', controller: 'franchises', only: %w(index show)
      resources 'industrial', controller: 'industrials', only: %w(index show)
      resources 'land', controller: 'lands', only: %w(index show)
      resources 'offices', only: %w(index show)
      resources 'retail', only: %w(index show)
    end
  end

  resources :users
end

app/views/layouts/_footer.html.erb
<div class="footer fixed">
  <div class="pull-right">
    <strong>Copyright</strong> Databank &copy; 2013-2017
  </div>
  <div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="nav-header">
        <div class="dropdown profile-element">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="clear">
              <span class="block m-t-xs">
                <h2 class="font-bold m-t-none">Databank</h2>
            </span>
          </a>
          <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li><a href="#">Logout</a></li>
          </ul>
        </div>
        <div class="logo-element">
          IN+
        </div>
      </li>
      <li class="<%= 'active' unless controller_path == 'users' %>">
        <%= link_to insider_search_root_path do %>
        <i class="fa fa-search"></i> <span class="nav-label">Search</span>
        <% end %>
      </li>
      <% if policy(User).index? %>
        <li class="<%= 'active' if controller_path == 'users' %>">
          <%= link_to users_path do %>
          <i class="fa fa-group"></i> <span class="nav-label">Users</span>
          <% end %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
  <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <li>
        <a href="<%= insider_logout_path %>">
          <i class="fa fa-sign-out"></i> Log out
        </a>
      </li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Databank Insider Reports</title>

  <!-- Main css styles -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Wrapper-->
  <div id="wrapper">

    <!-- Navigation -->
    <%= render 'layouts/navigation' %>

    <!-- Page wraper -->
    <div id="page-wrapper" class="gray-bg">

      <!-- Page wrapper -->
      <%= render 'layouts/topnavbar' %>

      <%= flash_messages %>

      <!-- Main view  -->
      <%= yield %>

      <!-- Footer -->
      <%= render 'layouts/footer' %>

    </div>
    <!-- End page wrapper-->

  </div>
  <!-- End wrapper-->

</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Databank Insider Reports</title>

  <!-- Main css styles -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body class="gray-bg">
  <%= yield %>
</body>
</html>